Repository OpenMS/OpenMS, pull requests merged in 2018-08, with the labels that each got.

#3510 void MzIdentMLFile::load(const String& filename, Identification& id) is broken
  src/openms/include/OpenMS/FORMAT/MzIdentMLFile.h
  src/openms/source/FORMAT/MzIdentMLFile.cpp
  src/pyOpenMS/pxds/MzIdentMLFile.pxd
  src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp
Labels: defect, major

#3670 [FIX] allow multiple array names for IM
  src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
Labels: enhancement

#3703 [FIX] annotate "spectra_data"
  src/tests/topp/FeatureFinderMetabo_1_output.featureXML
  src/tests/topp/FeatureFinderMetabo_2_noEPD_output.featureXML
  src/tests/topp/FeatureFinderMetabo_4_output.featureXML
  src/topp/FeatureFinderMetabo.cpp
Labels: defect

#3702 [FIX] annotate "spectra_data"
  src/tests/topp/FeatureFinderMetabo_1_output.featureXML
  src/tests/topp/FeatureFinderMetabo_2_noEPD_output.featureXML
  src/tests/topp/FeatureFinderMetabo_4_output.featureXML
  src/topp/FeatureFinderMetabo.cpp
Labels: defect
