Repository OpenMS/OpenMS, pull requests merged in 2020-01, with the labels that each got.

#4453 Feature/matrix py
  src/pyOpenMS/addons/MatrixDouble.pyx
  src/pyOpenMS/pxds/Matrix.pxd
Labels: pyOpenMS

#4447 Feature/tsg
  src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h
  src/openms/source/CHEMISTRY/TheoreticalSpectrumGenerator.cpp
  src/openms/source/KERNEL/MSSpectrum.cpp
  src/tests/class_tests/openms/source/CoarseIsotopeDistribution_test.cpp
  src/tests/class_tests/openms/source/CompNovoIdentificationCID_test.cpp
  src/tests/class_tests/openms/source/CompNovoIonScoringCID_test.cpp
  src/tests/class_tests/openms/source/CompNovoIonScoring_test.cpp
  src/tests/class_tests/openms/source/Deisotoper_test.cpp
  src/tests/class_tests/openms/source/FineIsotopeDistribution_test.cpp
  src/tests/class_tests/openms/source/TheoreticalSpectrumGenerator_test.cpp
Labels: Performance

#4482 [Improvement] FeatureFindingMetabo improved isotope detection
  src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureFindingMetabo.h
  src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
  src/tests/class_tests/openms/source/FeatureFindingMetabo_test.cpp
Labels: enhancement
