Repository OpenMS/OpenMS, pull requests merged in 2022-05, with the labels that each got.

#6090 added funding.yml
  .github/FUNDING.yml
Labels: NoJenkins, community

#6064 Season of Docs application - My edits
  doc/TOPP_tutorial/TOPP_concepts.doxygen
  doc/code_examples/Tutorial_AASequence.cpp
  doc/doxygen/public/QuickStart.doxygen
  src/openms/include/OpenMS/ANALYSIS/SEQUENCE/NeedlemanWunsch.h
Labels: NoJenkins

#6125 [FIX/PYOPENMS] update min. req. autowrap version
  src/pyOpenMS/CMakeLists.txt
Labels: pyOpenMS, NoJenkins
