Repository OpenMS/OpenMS, pull requests merged in 2022-04, with the labels that each got.

#6024 [Feature] Wrap IonIdentityMolecularNetworking
  src/pyOpenMS/pxds/IonIdentityMolecularNetworking.pxd
  src/pyOpenMS/tests/unittests/test000.py
Labels: pyOpenMS, metabolomics

#6041 [FIX,PYOMS,TYPING] add global imports to every pyi
  src/pyOpenMS/CMakeLists.txt
  src/pyOpenMS/fix_pyi_imports.py
Labels: NoJenkins

#6053 [FIX] DecoyDatabase detects already decoy'd DBs
  AUTHORS
  src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h
  src/tests/class_tests/openms/data/FASTAContainer_test.fasta
  src/tests/class_tests/openms/source/FASTAContainer_test.cpp
  src/tests/topp/CMakeLists.txt
  src/tests/topp/DecoyDatabase_2_out.fasta
  src/tests/topp/DecoyDatabase_3_out.fasta
  src/tests/topp/DecoyDatabase_4_out.fasta
  src/tests/topp/DecoyDatabase_5.fasta
  src/tests/topp/DecoyDatabase_6.fasta
  src/utils/DecoyDatabase.cpp
Labels: usability

#6076 Update PULL_REQUEST_TEMPLATE.md with information on reformat
  PULL_REQUEST_TEMPLATE.md
Labels: NoJenkins

#5915 Uncomment wrapping of other operators in Empirical Formula
  src/pyOpenMS/pxds/EmpiricalFormula.pxd
Labels: NoJenkins
