Repository OpenMS/OpenMS, pull requests merged in 2024-02, with the labels that each got.

#7325 fix nightly
  src/topp/executables.cmake
Labels: enhancement, Review effort [1-5]: 1

#7327 Use private key in nightly action to be able to trigger other workflow
  .github/workflows/update_nightly.yml
Labels: enhancement, Review effort [1-5]: 1

#7329 Stop KNIME site building multiple times on linux in GHA
  .github/workflows/openms_ci_matrix_full.yml
Labels: enhancement

#7326 remove matrix utils. replace OpenMS matrix class with eigen matrix
  cmake/cmake_findExternalLibs.cmake
  src/openms/CMakeLists.txt
  src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMScoring.h
  src/openms/include/OpenMS/ANALYSIS/QUANTITATION/ItraqConstants.h
  src/openms/include/OpenMS/DATASTRUCTURES/Matrix.h
  src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h
  src/openms/include/OpenMS/DATASTRUCTURES/Utils/sources.cmake
  src/openms/include/OpenMS/MATH/MISC/BilinearInterpolation.h
  src/openms/source/ANALYSIS/OPENSWATH/MRMScoring.cpp
  src/openms/source/ANALYSIS/QUANTITATION/IsobaricIsotopeCorrector.cpp
  src/openms/source/ANALYSIS/QUANTITATION/IsobaricQuantitationMethod.cpp
  src/openms/source/ANALYSIS/QUANTITATION/IsotopeLabelingMDVs.cpp
  src/openms/source/ANALYSIS/QUANTITATION/ItraqConstants.cpp
  src/openms/source/ANALYSIS/TOPDOWN/FLASHDeconvAlgorithm.cpp
  src/openms/source/COMPARISON/SPECTRA/PeakAlignment.cpp
  src/openms/source/MATH/MISC/NonNegativeLeastSquaresSolver.cpp
  src/pyOpenMS/pxds/Matrix.pxd
  src/tests/class_tests/openms/executables.cmake
  src/tests/class_tests/openms/source/BilinearInterpolation_test.cpp
  src/tests/class_tests/openms/source/IsobaricQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/IsotopeLabelingMDVs_test.cpp
  src/tests/class_tests/openms/source/ItraqConstants_test.cpp
  src/tests/class_tests/openms/source/ItraqEightPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/ItraqFourPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/MRMScoring_test.cpp
  src/tests/class_tests/openms/source/MatrixUtils_test.cpp
  src/tests/class_tests/openms/source/Matrix_test.cpp
  src/tests/class_tests/openms/source/NonNegativeLeastSquaresSolver_test.cpp
  src/tests/class_tests/openms/source/TMTEighteenPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/TMTElevenPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/TMTSixPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/TMTSixteenPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/TMTTenPlexQuantitationMethod_test.cpp
  src/topp/ImageCreator.cpp
Labels: enhancement, Review effort [1-5]: 4
