Repository OpenMS/OpenMS, pull requests merged in 2024-05, with the labels that each got.

#7482 Move contrib from abibuilder to GitHub
  .github/workflows/openms_ci_matrix_full.yml
  AUTHORS
Labels: enhancement, Review effort [1-5]: 2

#7484 fix compile warnings
  src/openms/include/OpenMS/ANALYSIS/OPENSWATH/IonMobilityScoring.h
  src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathScoring.h
Labels: Review effort [1-5]: 2, bug_fix

#7483 update citations
  README.md
  doc/doxygen/public/developer_tutorial.doxygen
  src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
  src/tests/class_tests/openms/data/ParamCTDFile_test_writeCTDToStream.ctd
  src/tests/class_tests/openms/source/ParamCTDFile_test.cpp
Labels: enhancement, Review effort [1-5]: 2

#7481 [Feature] DataFrame export for MSSpectrum and MSChromatogram
  src/pyOpenMS/pyopenms/_dataframes.py
  src/pyOpenMS/tests/unittests/test000.py
Labels: enhancement, Review effort [1-5]: 4, tests

#7490 make IonName(s) consistent. remove old fragmentselectioncode
  doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp
  src/openms/include/OpenMS/ANALYSIS/MRM/MRMFragmentSelection.h
  src/openms/include/OpenMS/ANALYSIS/MRM/sources.cmake
  src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h
  src/openms/include/OpenMS/CONCEPT/Constants.h
  src/openms/source/ANALYSIS/MRM/MRMFragmentSelection.cpp
  src/openms/source/ANALYSIS/MRM/sources.cmake
  src/openms/source/CHEMISTRY/NucleicAcidSpectrumGenerator.cpp
  src/openms/source/CHEMISTRY/SpectrumAnnotator.cpp
  src/openms/source/CHEMISTRY/TheoreticalSpectrumGenerator.cpp
  src/openms/source/CHEMISTRY/TheoreticalSpectrumGeneratorXLMS.cpp
  src/openms/source/FORMAT/MSPFile.cpp
  src/pyOpenMS/pxds/MRMFragmentSelection.pxd
  src/tests/class_tests/openms/executables.cmake
  src/tests/class_tests/openms/source/MRMFragmentSelection_test.cpp
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#7491 Wrap getvalidstrings
  src/pyOpenMS/pxds/Param.pxd
  src/pyOpenMS/tests/unittests/test000.py
Labels: enhancement, Review effort [1-5]: 2

#7492 make more parameters advanced in MetaProSIP
  src/topp/MetaProSIP.cpp
Labels: enhancement, Review effort [1-5]: 2

#7486 Added support for RNAse4 digestion of RNA. Fixed buggy regex for prot…
  share/OpenMS/CHEMISTRY/Enzymes.xml
  share/OpenMS/CHEMISTRY/Enzymes_RNA.xml
  src/openms/include/OpenMS/CHEMISTRY/RNaseDigestion.h
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#7493 Update update_nightly.yml
  .github/workflows/openms_ci_matrix_full.yml
  .github/workflows/update_nightly.yml
Labels: enhancement, Review effort [1-5]: 2
