Repository OpenMS/OpenMS, pull requests merged in 2024-09, with the labels that each got.

#7575 update Windows release notes
  cmake/Windows/ReleaseNotes.txt
Labels: Documentation, Review effort [1-5]: 1

#7573 fix MSIP part in KNIME
  src/topp/MetaProSIP.cpp
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7546 [FIX] OpenSwath: error in PASEF window determination
  CHANGELOG
  src/openms/include/OpenMS/FORMAT/SwathFile.h
  src/openms/source/FORMAT/SwathFile.cpp
  src/openswathalgo/include/OpenMS/OPENSWATHALGO/DATAACCESS/SwathMap.h
  src/tests/class_tests/openswathalgo/CMakeLists.txt
  src/tests/class_tests/openswathalgo/SwathMap_test.cpp
Labels: Bug fix, Review effort [1-5]: 2

#7580 Update openms_ci_matrix_full.yml
  .github/workflows/openms_ci_matrix_full.yml
Labels: enhancement, Review effort [1-5]: 1

#7585 TOPPView: open idXML in same layer as underlying data, if raw mzML is detected …
  src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
  src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
Labels: enhancement, Review effort [1-5]: 2

#7584 Defining more enzymes in OpenMS Comet and SAGE adaptor
  share/OpenMS/CHEMISTRY/Enzymes.xml
  src/topp/CometAdapter.cpp
  src/topp/SageAdapter.cpp
Labels: enhancement, Review effort [1-5]: 2
