Repository OpenMS/OpenMS, pull requests merged in 2024-07, with the labels that each got.

#7533 Update changelog with the help of tools/changelog_helper.sh
  CHANGELOG
Labels: enhancement, Documentation, Review effort [1-5]: 4

#7538 Update authors since 3.1.0
  AUTHORS
Labels: Documentation, Review effort [1-5]: 1

#7529 Add zip option for packaging
  CMakeLists.txt
  cmake/package_deb.cmake
  cmake/package_dragndrop_dmg.cmake
  cmake/package_mac_productbuild.cmake
  cmake/package_nsis.cmake
  cmake/package_rpm.cmake
Labels: enhancement, blocker, Review effort [1-5]: 3

#7540 CometAdapter fix for Comet 2024.01.0
  CHANGELOG
  src/topp/CometAdapter.cpp
Labels: Documentation, Bug fix, Review effort [1-5]: 3

#7541 IDFilter: new default values ('nan') for filtering by score
  CHANGELOG
  src/tests/topp/CMakeLists.txt
  src/topp/IDFilter.cpp
Labels: Bug fix, Review effort [1-5]: 3, tests

#7534 add html in selectversion.js
  doc/doxygen/common/selectversion.js
Labels: enhancement, Review effort [1-5]: 1

#7547 up minimal boost version to 1.74
  cmake/build_system_macros.cmake
  cmake/cmake_findExternalLibs.cmake
  doc/doxygen/install/install-linux.doxygen
Labels: enhancement, Documentation, Review effort [1-5]: 2

#7553 Update openms_ci_matrix_full.yml
  .github/workflows/openms_ci_matrix_full.yml
Labels: Review effort [1-5]: 1, configuration changes
