Repository OpenMS/OpenMS, pull requests merged in 2024-12, with the labels that each got.

#7724 add final to iterators and remove unneeded virtual
  src/openms/include/OpenMS/CHEMISTRY/AASequence.h
Labels: Review effort [1-5]: 2

#7728 add some debug output
  src/tests/class_tests/openms/source/TheoreticalSpectrumGenerator_test.cpp
Labels: Review effort [1-5]: 2

#7733 Add signing identity to cibuild.cmake
  tools/ci/cibuild.cmake
Labels: Review effort [1-5]: 1

#7739 fix Dockerfile
  .github/workflows/containerdeploy.yml
  dockerfiles/Dockerfile
Labels: Review effort [1-5]: 3

#7740 Use adhoc mac signing identity
  CMakeLists.txt
Labels: Review effort [1-5]: 2

#7736 SequenceCoverageCalculator: write annotated proteins to idXML
  src/topp/SequenceCoverageCalculator.cpp
Labels: Review effort [1-5]: 3

#7747 fix pyOpenMS CMakeLists.txt
  src/pyOpenMS/CMakeLists.txt
Labels: Review effort [1-5]: 1

#7743 put the cwl files in the right folder and generate them whenever we b…
  .github/workflows/openms_ci_matrix_full.yml
  CMakeLists.txt
  CTestConfig.cmake
  PULL_REQUEST_TEMPLATE.md
  cmake/cwl_generation.cmake
  doc/doxygen/public/developer_tutorial.doxygen
  tools/ci/cibuild.cmake
  tools/ci/cipackage.cmake
  tools/ci/citest.cmake
  tools/ci/lnx-cibuild.sh
  tools/ci/osx-cibuild.sh
Labels: Review effort [1-5]: 2

#7752 Choco's CMake 3.31.2 is bugged. Force use of 3.31.1
  .github/workflows/openms_ci_matrix_full.yml
Labels: Review effort [1-5]: 1

#7751 https://bugreports.qt.io/browse/QTBUG-110118 marked as fixed in qt6 r…
  cmake/cmake_findExternalLibs.cmake
Labels: Review effort [1-5]: 2

#7754 Ignore warnings in extern libs
  src/openms/include/OpenMS/KERNEL/MSExperiment.h
  tools/ci/cibuild.cmake
Labels: Review effort [1-5]: 1
