Repository OpenMS/OpenMS, pull requests merged in 2024-11, with the labels that each got.

#7323 removes need for PSMFeatureExtractor by always adding percolator features
  CHANGELOG
  src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp
  src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp
  src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp
  src/tests/class_tests/openms/data/xtandem.topperc.idXML
  src/tests/class_tests/openms/data/xtandem.topperc_check.idXML
  src/tests/topp/CMakeLists.txt
  src/tests/topp/PSMFeatureExtractor_1_out.idXML
  src/tests/topp/PSMFeatureExtractor_2_out.mzid
  src/tests/topp/PSMFeatureExtractor_3_out.idXML
  src/tests/topp/SimpleSearchEngine_1_out.idXML
  src/tests/topp/SimpleSearchEngine_2_out.idXML
  src/tests/topp/THIRDPARTY/CometAdapter_1_out.idXML
  src/tests/topp/THIRDPARTY/CometAdapter_2_out.idXML
  src/tests/topp/THIRDPARTY/CometAdapter_3_out.idXML
  src/tests/topp/THIRDPARTY/CometAdapter_4_out.idXML
  src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML
  src/tests/topp/THIRDPARTY/XTandemAdapter_1_out.idXML
  src/tests/topp/THIRDPARTY/XTandemAdapter_2_out.idXML
  src/tests/topp/THIRDPARTY/XTandemAdapter_3_out.idXML
  src/tests/topp/THIRDPARTY/third_party_tests.cmake
  src/topp/CometAdapter.cpp
  src/topp/MSFraggerAdapter.cpp
  src/topp/MSGFPlusAdapter.cpp
  src/topp/MascotAdapterOnline.cpp
  src/topp/PSMFeatureExtractor.cpp
  src/topp/XTandemAdapter.cpp
Labels: enhancement, Review effort [1-5]: 3

#7645 improve file list comparison
  src/openms/include/OpenMS/SYSTEM/File.h
  src/openms/source/SYSTEM/File.cpp
  src/tests/class_tests/openms/source/File_test.cpp
  src/topp/ProteomicsLFQ.cpp
Labels: Review effort [1-5]: 3

#7648 fix warning in DatabaseFilter.cpp
  src/topp/DatabaseFilter.cpp
Labels: Review effort [1-5]: 1

#7649 fix test_equal code (allow comparison of enums)
  src/openms/include/OpenMS/CONCEPT/ClassTest.h
  src/tests/class_tests/openms/source/ClassTest_test.cpp
Labels: Review effort [1-5]: 2

#7639 Correctly do the unit tests in pyopenms-wheels
  .github/workflows/pyopenms-wheels.yml
  src/openms/include/OpenMS/config.h.in
  src/pyOpenMS/pxds/RNaseDB.pxd
  src/pyOpenMS/requirements_bld.txt
  src/pyOpenMS/tests/unittests/test000.py
  src/tests/class_tests/openms/source/File_test.cpp
  tools/ci/cibuild.cmake
Labels: Review effort [1-5]: 2

#7620 Update containerdeploy.yml to match Release/
  .github/workflows/containerdeploy.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7650 more convenient constructor for AASequence in Python
  src/openms/include/OpenMS/CHEMISTRY/AASequence.h
  src/openms/source/CHEMISTRY/AASequence.cpp
  src/pyOpenMS/pxds/AASequence.pxd
  src/pyOpenMS/tests/unittests/test000.py
Labels: Review effort [1-5]: 3

#7654 fix some warnings
  src/openms/source/ANALYSIS/ID/IDMapper.cpp
  src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureSelector.cpp
  src/openms/source/FORMAT/MSstatsFile.cpp
  src/openms/source/FORMAT/PercolatorInfile.cpp
  src/openms/source/FORMAT/QcMLFile.cpp
  src/openms/source/FORMAT/TextFile.cpp
  src/openms/source/IONMOBILITY/IMDataConverter.cpp
  src/openms/source/METADATA/ExperimentalDesign.cpp
  src/openms/source/QC/DBSuitability.cpp
  src/openms/source/QC/MQMsmsExporter.cpp
Labels: Review effort [1-5]: 2

#7643 added annotate_features param in Deisotoper.cpp
  src/openms/include/OpenMS/PROCESSING/DEISOTOPING/Deisotoper.h
  src/openms/source/PROCESSING/DEISOTOPING/Deisotoper.cpp
  src/pyOpenMS/pxds/Deisotoper.pxd
Labels: Review effort [1-5]: 2

#7658 [refactor] removed legacy SWATH chromatogram extraction code
  src/openms/include/OpenMS/ANALYSIS/OPENSWATH/ChromatogramExtractor.h
  src/pyOpenMS/pxds/ChromatogramExtractor.pxd
  src/tests/class_tests/openms/source/ChromatogramExtractor_test.cpp
Labels: Review effort [1-5]: 3

#7660 add trivial devcontainer config
  .devcontainer/devcontainer.json
  README.md
Labels: Review effort [1-5]: 1

#7669 [DOC] Include common CMake flags documentation as doxygen
  AUTHORS
  doc/doxygen/install/install-linux.doxygen
  doc/doxygen/install/install-macs.doxygen
  doc/doxygen/install/install-win.doxygen
Labels: Review effort [1-5]: 1

#7670 add additional wrapper and fix test
  src/pyOpenMS/pxds/ChromatogramExtractor.pxd
  src/pyOpenMS/tests/unittests/test_ChromatogramExtractor.py
Labels: Review effort [1-5]: 3

#7671 Fix RPATH creation in deb package
  .gitignore
  CMakeLists.txt
  cmake/package_deb.cmake
  cmake/package_general.cmake
Labels: Review effort [1-5]: 2

#7673 fix TRFP
  src/topp/FileConverter.cpp
Labels: Review effort [1-5]: 2

#7674 TRFP update test file
  src/tests/topp/THIRDPARTY/ginkgotoxin-ms-switching_out.mzML
Labels: Review effort [1-5]: 2

#7664 Pre 3.3 fixes
  CHANGELOG
  tools/ACTIVE_MAINTAINERS
Labels: Review effort [1-5]: 3

#7678 deployment: create bioconda deploy action
  .github/workflows/bioconda_deploy.yaml
Labels: Review effort [1-5]: 3

#7683 Throw warning if package is defined with enable_x_testing
  src/tests/CMakeLists.txt
Labels: Review effort [1-5]: 1

#7685 Now that we aren't passing the package type during the build just set…
  CMakeLists.txt
  cmake/package_deb.cmake
Labels: Review effort [1-5]: 2

#7693 Revert "conda: try to add windows builds"
  .github/workflows/bioconda_deploy.yaml
Labels: Review effort [1-5]: 3

#7697 add missing ion names to Residue.cpp
  src/openms/source/CHEMISTRY/Residue.cpp
Labels: Review effort [1-5]: 2

#7699 Update pyopenms-wheels.yml
  .github/workflows/pyopenms-wheels.yml
Labels: Review effort [1-5]: 2

#7700 Apply fix for msvc issue
  .github/workflows/pyopenms-wheels.yml
Labels: Review effort [1-5]: 2

#7679 Update update_version_numbers.yml
  .github/workflows/update_version_numbers.yml
  tools/update_ini_files_OpenMS_version.sh
Labels: Review effort [1-5]: 2

#7587 Update/OpenSwathWorkflow IonMobilityScoring Mobilogram Datastructure
  CHANGELOG
  src/openms/include/OpenMS/ANALYSIS/OPENSWATH/IonMobilityScoring.h
  src/openms/source/ANALYSIS/OPENSWATH/IonMobilityScoring.cpp
Labels: enhancement, Review effort [1-5]: 3

#7721 check if change introduced in earler commit is source of error on MSVC AASequence.h
  src/openms/include/OpenMS/CHEMISTRY/AASequence.h
Labels: Review effort [1-5]: 2
