Repository OpenMS/OpenMS, pull requests merged in 2024-06, with the labels that each got.

#7503 Build pyopenmswheels nightly
  .github/workflows/update_nightly.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7502 always install doxygen
  .github/workflows/openms_ci_matrix_full.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7508 parse relationship as xref
  src/openms/source/FORMAT/ControlledVocabulary.cpp
Labels: enhancement, Review effort [1-5]: 3

#7489 [Feature] Export ion annotations for MSSpectrum DataFrame
  src/pyOpenMS/pyopenms/_dataframes.py
  src/pyOpenMS/tests/unittests/test000.py
Labels: enhancement, Review effort [1-5]: 3, tests

#7512 fix etcid encoding with supplemental cv term
  src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#7515 Set pyopenms numpy install<2.0
  .github/workflows/pyopenms-wheels.yml
  .github/workflows/test_pyopenms.yml
  src/pyOpenMS/setup.py
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7516 Numpy install 1.26.4 or earlier
  .github/workflows/pyopenms-wheels.yml
  .github/workflows/test_pyopenms.yml
  src/pyOpenMS/setup.py
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7517 Fix install numpy <=1.26.4
  .github/workflows/pyopenms-wheels.yml
Labels: Bug fix, Review effort [1-5]: 1, configuration changes

#7519 Update pyopenms test actions
  .github/workflows/test_pyopenms.yml
Labels: enhancement, dependencies, Review effort [1-5]: 2

#7518 use contrib from github
  .github/workflows/pyopenms-wheels.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7520 Update openms_ci_matrix_full.yml to properly set source archive name
  .github/workflows/openms_ci_matrix_full.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#7522 Pypifixes
  .github/workflows/pyopenms-wheels.yml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#7523 Update CHANGELOG
  CHANGELOG
Labels: Documentation, Review effort [1-5]: 1

#7524 Deprecate XTandemAdapter.cpp
  src/topp/XTandemAdapter.cpp
Labels: Documentation, Review effort [1-5]: 1
