Repository OpenMS/OpenMS, pull requests merged in 2024-10, with the labels that each got.

#7601 add isobaric correction defaults for tmt6plex and 11plex
  src/openms/source/ANALYSIS/QUANTITATION/IsobaricIsotopeCorrector.cpp
  src/openms/source/ANALYSIS/QUANTITATION/TMTElevenPlexQuantitationMethod.cpp
  src/openms/source/ANALYSIS/QUANTITATION/TMTSixPlexQuantitationMethod.cpp
  src/tests/class_tests/openms/source/TMTElevenPlexQuantitationMethod_test.cpp
  src/tests/class_tests/openms/source/TMTSixPlexQuantitationMethod_test.cpp
  src/tests/topp/TMTElevenPlexMethod_test.consensusXML
  src/tests/topp/TMTElevenPlexMethod_test.ini
Labels: Review effort [1-5]: 2, bug_fix

#7594 FeatureFinderMetabo: param to toggle reporting smoothed intensities
  AUTHORS
  CHANGELOG
  src/openms/include/OpenMS/FEATUREFINDER/FeatureFindingMetabo.h
  src/openms/source/FEATUREFINDER/FeatureFindingMetabo.cpp
Labels: enhancement, Review effort [1-5]: 2

#7609 better variable names
  src/openms/source/FORMAT/MzTabFile.cpp
Labels: enhancement, Review effort [1-5]: 2

#7618 expose eigen downstream
  cmake/OpenMSConfig.cmake.in
Labels: enhancement, Review effort [1-5]: 2

#7619 fix for CI on mac x86
  .github/workflows/openms_ci_matrix_full.yml
Labels: Review effort [1-5]: 1, configuration changes

#7616 Fix remove old pyds
  .github/workflows/pyopenms-wheels.yml
Labels: Review effort [1-5]: 1, bug_fix, configuration changes

#7621 Categorize branch
  .github/workflows/openms_ci_matrix_full.yml
  src/openms/source/APPLICATIONS/ToolHandler.cpp
  src/topp/OpenSwathWorkflow.cpp
  src/topp/QCCalculator.cpp
  src/topp/QCExporter.cpp
  src/topp/QCExtractor.cpp
  src/topp/QCImporter.cpp
  src/topp/QCMerger.cpp
  src/topp/QCShrinker.cpp
  src/topp/SimpleSearchEngine.cpp
  src/topp/SiriusExport.cpp
  src/topp/TICCalculator.cpp
Labels: enhancement, Review effort [1-5]: 2

#7622 fix KNIME categories
  src/openms/source/APPLICATIONS/ToolHandler.cpp
  src/tests/class_tests/openms/source/ToolHandler_test.cpp
Labels: enhancement, Review effort [1-5]: 2

#7624 add quick check for almost certain out of memory error
  src/openms/source/FEATUREFINDER/MultiplexClustering.cpp
Labels: Review effort [1-5]: 2

#7625 Cmake fix
  cmake/build_system_macros.cmake
  src/openms/configh.cmake
  src/tests/topp/THIRDPARTY/SageAdapter_1_out.idXML
  src/tests/topp/THIRDPARTY/third_party_tests.cmake
Labels: Review effort [1-5]: 2

#7626 OpenMS does not compile when using GLPK (instead of COINOR)
  CHANGELOG
  cmake/Modules/FindCOIN.cmake
  cmake/cmake_findExternalLibs.cmake
  src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h
  src/openms/include/OpenMS/config.h.in
  src/openms/source/DATASTRUCTURES/LPWrapper.cpp
  src/tests/class_tests/openms/source/LPWrapper_test.cpp
  src/topp/OpenMSInfo.cpp
Labels: Review effort [1-5]: 2

#7627 MzTab: preallocate enough memory instead of allocating in the loops
  src/openms/source/FEATUREFINDER/MultiplexClustering.cpp
  src/openms/source/FORMAT/MzTab.cpp
Labels: Review effort [1-5]: 2

#7539 Build PyOpenMS with numpy2
  .github/workflows/pyopenms-wheels.yml
  src/pyOpenMS/requirements_bld.txt
  src/pyOpenMS/setup.py
Labels: enhancement, dependencies, Review effort [1-5]: 2

#7638 Add check for pandas in cmake
  src/pyOpenMS/CMakeLists.txt
Labels: Review effort [1-5]: 2

#7630 additional convenience functions for MSExperiment
  src/openms/include/OpenMS/KERNEL/MSExperiment.h
  src/openms/include/OpenMS/KERNEL/MSSpectrum.h
  src/openms/include/OpenMS/KERNEL/RangeManager.h
  src/openms/source/IONMOBILITY/IMDataConverter.cpp
  src/openms/source/KERNEL/MSSpectrum.cpp
  src/openms_gui/source/VISUAL/Plot2DCanvas.cpp
  src/pyOpenMS/addons/ADD_TO_ALL.pyx
  src/pyOpenMS/addons/MSExperiment.pyx
  src/pyOpenMS/addons/MSSpectrum.pyx
  src/pyOpenMS/addons/MatrixDouble.pyx
  src/pyOpenMS/pxds/MSExperiment.pxd
  src/pyOpenMS/pxds/RangeManager.pxd
  src/pyOpenMS/pyopenms/_dataframes.py
  src/pyOpenMS/tests/unittests/test000.py
  src/tests/class_tests/openms/source/MSExperiment_test.cpp
  src/tests/class_tests/openms/source/MSSpectrum_test.cpp
Labels: Review effort [1-5]: 4
