Repository OpenMS/OpenMS, pull requests merged in 2025-03, with the labels that each got.

#7864 Fix/openswathscoring pxd
  CHANGELOG
  src/pyOpenMS/pxds/OpenSwathScoring.pxd
Labels: pyOpenMS, Bug fix

#7868 Fix: Doxygen Docs contain stty warning for TOPP tool output
  AUTHORS
  CHANGELOG
  doc/doxygen/parameters/TOPPDocumenter.cpp
Labels: Review effort 1/5

#7885 Fix: OSW, pass im_range to scoreIdentification method
  CHANGELOG
  src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h
  src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
Labels: OpenSwathAlgo, Bug fix

#7892 [SimpleSVM] Implement Pimpl idiom and remove direct libSVM dependencies
  src/openms/include/OpenMS/ML/SVM/SimpleSVM.h
  src/openms/source/ML/SVM/SimpleSVM.cpp
Labels: Review effort 3/5

#7895 added version change to changelog
  CHANGELOG
Labels: Review effort 1/5

#7915 Fix #7912: Make build instructions reachable in less than three click…
  AUTHORS
  CHANGELOG
  README.md
Labels: Review effort 1/5

#7927 remove: MascotAdapter
  CHANGELOG
  doc/doxygen/public/TOPP.doxygen
  src/openms/include/OpenMS/FORMAT/MascotInfile.h
  src/openms/include/OpenMS/FORMAT/sources.cmake
  src/openms/source/APPLICATIONS/ToolHandler.cpp
  src/openms/source/FORMAT/MascotInfile.cpp
  src/openms/source/FORMAT/sources.cmake
  src/pyOpenMS/pxds/MascotInfile.pxd
  src/tests/class_tests/openms/executables.cmake
  src/tests/class_tests/openms/source/MascotInfile_test.cpp
  src/tests/topp/CMakeLists.txt
  src/tests/topp/MascotAdapter_1_input.mzData
  src/tests/topp/MascotAdapter_1_output.mascot_in
  src/tests/topp/MascotAdapter_1_parameters.ini
  src/tests/topp/MascotAdapter_2_input.mascotXML
  src/tests/topp/MascotAdapter_2_output.idXML
  src/topp/FalseDiscoveryRate.cpp
  src/topp/HighResPrecursorMassCorrector.cpp
  src/topp/IDDecoyProbability.cpp
  src/topp/IDMapper.cpp
  src/topp/IDMerger.cpp
  src/topp/IDPosteriorErrorProbability.cpp
  src/topp/IDRTCalibration.cpp
  src/topp/MascotAdapter.cpp
  src/topp/PhosphoScoring.cpp
  src/topp/executables.cmake
Labels: Review effort 3/5

#7914 Added support for more Data-field
  src/openms/include/OpenMS/FORMAT/MascotGenericFile.h
Labels: Review effort 1/5
